# Generated by Django 2.1.4 on 2018-12-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisasi_nama', models.CharField(max_length=50)),
                ('organisasi_email', models.CharField(max_length=50)),
                ('organisasi_telepon', models.CharField(max_length=50)),
                ('organisasi_profile', models.TextField()),
            ],
        ),
    ]
