# Generated by Django 2.1.4 on 2018-12-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_organisasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berita_judul', models.CharField(max_length=100)),
                ('berita_isi', models.TextField()),
                ('berita_foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_foto', models.CharField(max_length=100)),
                ('gallery_caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan_nama', models.CharField(max_length=100)),
                ('kegiatan_deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekening_nomor', models.CharField(max_length=100)),
                ('rekening_nama', models.CharField(max_length=100)),
                ('rekening_bank', models.TextField()),
                ('rekening_gambar', models.CharField(max_length=100)),
            ],
        ),
    ]
