# Generated by Django 2.1.4 on 2018-12-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_berita_gallery_kegiatan_rekening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_foto',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
